### PR TITLE
Issue #55 - added version for windows platform

### PR DESCRIPTION
**Pull request by marek-knappe**

### CODE REVIEW

**Comment by marek-knappe** [comment]
@toricls  Can you approve that one? just small fix for issue #55 that I stumbled upon

**Comment by toricls** [comment]
Hi @marek-knappe! Unfortunately I'm not working for AWS anymore, but I believe @adamjkeller can review and merge this PR for us :D

**Comment by adamjkeller** [comment]
Hey @toricls! Nice to see you around these parts :-) 

@nathanpeck @maishsk should be able to help review and merge this PR. Thank you @marek-knappe for your patience here!

**Comment by nathanpeck** [comment]
Thanks a lot Marek!

**Review by nathanpeck — APPROVED** [review]

**Comment by maishsk** [comment]
LGTM 👍

**Review by maishsk — APPROVED** [review]
LGTM

**Pull request merged**
